// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.DataAccess;

namespace Weather.DataAccess.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20201126043521_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Weather.Domain.ZipCodeWeather", b =>
                {
                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Temparature")
                        .HasColumnType("int");

                    b.HasKey("ZipCode");

                    b.ToTable("ZipCodeWeather");
                });
#pragma warning restore 612, 618
        }
    }
}
